<?php
// SPDX-FileCopyrightText: 2026 [ernolf] Raphael Gradenwitz
// SPDX-License-Identifier: GPL-3.0-or-later

// Emit www/inc/dnsmasq_manpage.php: the per-directive help text of the
// dnsmasq(8) manual page as key => description. That file is only the
// fallback — inc/manpage.php reads the manual page of the running binary at
// runtime and carries the parser both paths share, so this tool is a thin
// wrapper around it.
//
// Usage:
//   php tools/gen-manpage.php [<dnsmasq.8[.gz]>] [<path to inc/manpage.php>]
//
// With no arguments it locates the manpage via `man -w dnsmasq` and filters to
// the keys declared in www/inc/dnsmasq_directives.php. The second argument is
// for running the tool detached from its checkout, e.g. piped into `php` on
// the machine that has the manual page installed. The manpage text is licensed
// GPL (dnsmasq), compatible with this project.

require_once($argv[2] ?? __DIR__ . '/../www/inc/manpage.php');

$src = $argv[1] ?? manpage_locate();
if ($src === null || !is_file($src)) {
    fwrite(STDERR, "dnsmasq manpage not found (give its path as argv[1])\n");
    exit(1);
}

// Keep only the keys the Configuration page knows.
$keep = [];
foreach (array_keys(dnsmasq_directives()) as $k) $keep[strtolower($k)] = true;

$map = manpage_parse(manpage_read($src), $keep);
$ver = trim((string) shell_exec('dnsmasq --version 2>/dev/null | head -1'));

$php  = "<?php\n";
$php .= "// SPDX-FileCopyrightText: 2026 [ernolf] Raphael Gradenwitz\n";
$php .= "// SPDX-License-Identifier: GPL-3.0-or-later\n\n";
$php .= "// Per-directive help text extracted from the dnsmasq(8) manual page\n";
$php .= "// (text licensed GPL, (c) Simon Kelley). Generated by tools/gen-manpage.php";
$php .= $ver !== '' ? "\n// from " . $ver . "." : ".";
$php .= "\n// Do not edit by hand; regenerate when the dnsmasq version changes.\n//\n";
$php .= "// This copy is the fallback: inc/manpage.php reads the manual page that is\n";
$php .= "// installed next to the running binary and uses this one only when the\n";
$php .= "// system carries none.\n\n";
$php .= "function dnsmasq_manpage_bundled(): array {\n    return [\n";
foreach ($map as $k => $v) {
    $php .= '        ' . var_export($k, true) . ' => ' . var_export($v, true) . ",\n";
}
$php .= "    ];\n}\n";

echo $php;
